### ISSUE TITLE
Need to clarify that the VCAP_SERVICES is different for DB2 Warehouse on Cloud and  Db2 on Cloud services.

### ISSUE THREAD

**Issue by prsahoo** [IBM-Cloud/cloud-sql-database#2]
Hi Henrik,

Thanks for creating nice applications.   I want to suggest a simple thing. I am not sure whether we should change the code or document it somewhere.  

In worldcities.py  the code states to read the VCAP_SERVICE env variable in this fashion.  
```
db2info = json.loads(os.environ['VCAP_SERVICES'])['dashDB'][0]
```
However this will work only for the Db2 Warehouse on Cloud ( Previously called dashDB)  and not for Db2 on Cloud ( Previously called dashDB For Transactions ).   So can we specify in the document somehwhere that is anybody is using the Db2 Lite plan or any other Db2 plan , they need to modify the code read the VCAP services in the following fashion.
```
db2info = json.loads(os.environ['VCAP_SERVICES'])['dashDB For Transactions'][0]
```

Thank you.

**Comment by data-henrik** [comment]
@prsahoo The tutorial uses Db2 Warehouse on Cloud, see https://console.bluemix.net/docs/tutorials/sql-database.html. Hence the code is written for that service. Obviously, using a different service requires adapting the service identifier.
There are no plans to change the database service or add options for another service. I will close the issue.
