### ISSUE TITLE
How to connect to IBM DB2 cloud using ibm-db 

### ISSUE THREAD

**Issue by SahooAshis** [IBM-Cloud/cloud-sql-database#4]
Can you please let me now the steps to how to connect to IBM DB2 cloud using ibm-db

**Comment by data-henrik** [comment]
The tutorial covers the overall steps and has sample code for the app. The Db2 database drivers and sample codes are available here: https://github.com/ibmdb/, the Node.js repo is here: https://github.com/ibmdb/node-ibm_db Check out the samples, ready for copy & paste.

**Comment by SahooAshis** [comment]
I have followed the steps but getting below error

```
 SQLCODE=-30081r] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "169.60.146.125".  Communication function detecting the error: "recv".  Protocol specific error code(s): "10054", "*", "0".  SQLSTATE=08001
```

Please find below the code
```
import ibm_db

dsn = 'DRIVER={IBM DB2 ODBC DRIVER};DATABASE=BLUEDB;HOSTNAME=54a2f15b-5c0f-46df-8954-7e38e612c2bd.c1ogj3sd0tgtu0lqde00.databases.appdomain.cloud;PORT=32733;PROTOCOL=TCPIP;UID=<userId>;PWD=<password>;'

try:
    con = ibm_db.connect(dsn,"","")
    print('Connected to DB2 successfully')
except:
    print(ibm_db.conn_errormsg())
```

The DB2 database is a free tier service on IBM Cloud.

**Comment by data-henrik** [comment]
Is your question related to the tutorial or to using the Db2 driver with that specific version of Db2 on Cloud?

**Comment by SahooAshis** [comment]
My question is how can we connect to DB2 IBM Cloud server?
